### ISSUE TITLE
Nightly build failed

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#117]
Run failed for master (51fcdd1)
Workflow: Nightly
Duration: 14 minutes and 55.0 seconds
Finished: 2020-09-21 18:21:59 UTC

**Comment by koonpeng** [comment]
This is caused by [this](https://github.com/osrf/rmf_core/commit/727048469f9ce14d6e76628dec96a84ca1ce99f9) commit in osrf/rmf_core.

The commit breaks eloquent support, so we need to move to foxy. But soss does not build in foxy due to fastrtps errors, an ugly workaround is to build fastrtps from source, or build soss in a separate container and hope that foxy messages are compatible with eloquent.

The other "solution" would be to wait till the api gateway is ready, then we will be able to ditch soss, solving this problem as well.

**Comment by koonpeng** [comment]
soss has been ditched but the new problem is now with rmf_core possibly related to this https://github.com/osrf/rmf_core/issues/129.

The short story is that rmf is using too much cpu and ram and the gh actions runner doesn't meet the requirements, causing tests to break.

**Comment by matiasbavera** [comment]
What do you think about temporarily removing the e2e test step from the flow or mark it as optional (maybe `continue-on-error: true`) and re-activate it when this https://github.com/osrf/rmf_core/issues/129 is fixed?

I mention this because we are receiving a ci error email on each PR we open/merge, etc even when the other tests are right. I'm concerned that we unconsciously downplay the error messages received by the CI because it has become a normal situation.

**Comment by koonpeng** [comment]
Let's wait and see for now, @mxgrey is working on improving the performance.

**Comment by koonpeng** [comment]
long await update: the unnecessary cpu saturation should be solved, but the tests are still failing because of recent update to the delivery and loop commands. rmf now uses a new dispatch system and no longer accepts the old commands.

**Comment by koonpeng** [comment]
fixed/workaround by removing commands panel #264
