### ISSUE TITLE
Robots: Robots without a state are not shown

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#166]
We are only displaying robot's with known state, so a robot that lost connection to rmf will then disappear from the dashboard. The robot's state also does not contain all the info that we need, for example, a robot's footprint is only available from the trajectory so we have to use a hardcoded value now.

**Comment by ChawinTan** [comment]
Seems like fleet manager is handling all the states of the robots. Can I assume that all robots returned by the resource manager will be at the same level? Or there is no need to display the icon but just display the robot in the omni-panel accordian, like the dispensers?

**Comment by koonpeng** [comment]
afaik, the robot resources only contains the icons, they do not list all the known robots in a map. I am not aware of any rmf interfaces that provides that atm.

**Comment by ChawinTan** [comment]
I see, so it differs from dispensers in that the location of all known dispensers is hardcoded in the json resource files due to rmf limitations whereas the known robots will be handled by rmf instead.

So for the case of robots, some sort of cache to store all known robots, and then referencing them later if they are disconnected would be more appropriate.

**Comment by cnboonhan** [comment]
Closing this as another development should be addressing this.
