### ISSUE TITLE
[throwaway/demo] Modifications to Tasks Tab

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#352]
- [x] Allow users to submit a batch of tasks from a json file
This is a feature that exists in `rmf_demos_panel` in `rmf_demos`. In the screenshot below, there is a text box on the right hand side which can be populated either by loading a json file with tasks or directly editing its contents. Then when the user clicks `Submit Task List` the dashboard should sequentially submit the tasks to the dispatcher
![image](https://user-images.githubusercontent.com/13482049/119433022-f541f400-bd47-11eb-843e-694dd5504986.png)

- [x] Allow users to cancel a task
This is another feature that exists in `rmf_demos_panel`. It is desirable to add a `Cancel Task` button to the task card that appears when a task is clicked on in the Tasks tab. When this button is clicked, the dashboard should make a service call to `/cancel_task`
![image](https://user-images.githubusercontent.com/13482049/119433808-8f566c00-bd49-11eb-8f1e-90ed76ac4cb7.png)

- [x] Cleanup task entries in Tasks tab
As seen in the screenshot above, there are several task entries but only `Loop0` is an actual task. The others are just phases of a `ResponsiveWait` task that is issued to idle robots automatically. This is probably happening because this list is being populated by listening to `/task_summaries` topic. Instead, we should get information on tasks by making a service call to `/get_tasks`. On a related note, it seems that the user needs to hit refresh each time to see the task list updated. It would be nice if this happened periodically. 
> This was accomplished by switching to `throwaway/demo` of `rmf_ros2` and then having the api-server subscribe to `/filtered_task_summaries` 

- [x] Customized list of waypoints for each task
When submitting a new task, the location dropdown currently features all the waypoints in the map. The desire is to customize this list for each task type so that only waypoints relevant to the task are displayed. Perhaps in a way similar to how its being done in `rmf_demos_panel` using json files stored in `rmf_demos_dashboard_resources`. 
![image](https://user-images.githubusercontent.com/13482049/119434496-dd1fa400-bd4a-11eb-9db4-bc306689653f.png)

- [x] ~~Update State of the task
The State of the task seems to always be  "Queued" even if the task is executing or has completed~~
![image](https://user-images.githubusercontent.com/13482049/119436349-9633ad80-bd4e-11eb-9d90-bdf11e032125.png)

- [x] ~~Add a "Description" column to the tasks in the Tasks tab.
Depending on the task type, populate its description. For example if it is a cleaning task, specify the zone that will be cleaned~~
![image](https://user-images.githubusercontent.com/13482049/119434982-e9583100-bd4b-11eb-9263-f78cc3b323b7.png)

**Comment by koonpeng** [comment]
> Allow users to submit a batch of tasks from a json file
I don't see an easy way to fake this without some extreme hardcoding, there is actually a upload file button hidden but it is not enabled because we are missing several components to make it usable.

> Cleanup task entries in Tasks tab
This is not easily fixable because of missing data from rmf. The server needs to keep track of each task in the database because we need to support querying, sorting and pagination. Using `/get_tasks` to download everything everytime is very heavy on the bandwidth and is not scalable in production when the task list is always growing. So the server must listen to `/task_summaries` to sync the tasks with the database. We can either stop publishing "ghost" tasks in `/task_summaries`, add querying, sorting and pagination support in `/get_tasks` or hardcode some values in the frontend. In the case of hardcoding, we need a filter to find out what tasks are supposed, not supposed to change, it should only be a few lines of changes.

Auto refresh is also not something that can be easily hardcoded/implemented. Some challenges needs to be addressed with regards to maintaining pagination when we refresh. This conflicts with some things like the requirement to sort by priority first , should we rearrange tasks when a new high priority task is assigned? The request to use `/get_tasks` here, with hundreds or thousands of tasks in production, we dont want to download the full list every x seconds (it can filter by task id, but we can't find new tasks added without downloading the full list), so this needs listening to `/task_summaries` currently.

> Customized list of waypoints for each task
rmf does not provide enough information to find the list of valid waypoints. Doing some hardcode json configurations is build time is ugly and not workable in production. We will need to maintain that list for each site, and it locks out many features, users cannot change the waypoints, add/remove waypoints etc without rebuilding/changing some "technical" json files. We might as well hardcode a list of waypoints in the frontend, it will be much easier.

The other issues should be relatively easy to address.

**Comment by Yadunund** [comment]
Many thanks @koonpeng  for the feedback.

> Using /get_tasks to download everything everytime is very heavy on the bandwidth and is not scalable in production when the task list is always growing.

Thanks for explaining this. I understand the poor scalability with this approach. But for our demo we won't expect to have more than a 100 tasks. So perhaps the bandwidth will not be too high to repeatedly call this? (Same with having a periodic refresh) Totally fine with the options that you have proposed as well.

**Comment by tanyouliang95** [comment]
@koonpeng Thanks for the feedback 
> Allow users to submit a batch of tasks from a json file

For the time being, Is it possible to add an async operation at the client-side to submit a request to the api-server? 

> Cleanup task entries in Tasks Tab

Understand the concern, and I totally agree. Maybe the long-term plan here is to have the `rmf dispatcher node` publishing out a ros msg: which consists of a list of aggregated active `task_summaries `. (similar to how we manage `robot_states` and `fleet_states`). For the demo sake, we can do some hack in filtering out some of these at the client-side.

> Customized list of waypoints for each task

Yes, currently the one which we are concerned about is the "clean_zones", specifically for Clean Task. Essentially, we will only want to have a dropdown of waypoints that are relevant to the selected task. Currently, the information is available as s `building.yaml`, but not populated the rostopic; `/map`. One way is to populate the [GraphNode](https://github.com/open-rmf/rmf_building_map_msgs/blob/main/rmf_building_map_msgs/msg/GraphNode.msg) param with the relevant information about the waypoint.

**Comment by koonpeng** [comment]
> Thanks for explaining this. I understand the poor scalability with this approach. But for our demo we won't expect to have more than a 100 tasks. So perhaps the bandwidth will not be too high to repeatedly call this? (Same with having a periodic refresh) Totally fine with the options that you have proposed as well.

It's possible for the demo, but I have reservation about implement these features which we know will cause technical debt. Regarding the `ResponsiveWait` tasks, I think we will be better off just hard coding a list of task to be hidden, or stop publishing these "ghost tasks" in `/task_summaries`. We will have to use the `/task_summaries` for auto refresh, so using `/get_tasks` exclusively is not possible.

> For the time being, Is it possible to add an async operation at the client-side to submit a request to the api-server?

I'm working on it now.

> Understand the concern, and I totally agree. Maybe the long-term plan here is to have the rmf dispatcher node publishing out a ros msg: which consists of a list of aggregated active task_summaries . (similar to how we manage robot_states and fleet_states). For the demo sake, we can do some hack in filtering out some of these at the client-side.

I thought that is what `/task_summaries` does? Except that it publishes when things change instead of periodically. This is probably better as I doubt the tasks summaries will be changing very much.

> Yes, currently the one which we are concerned about is the "clean_zones", specifically for Clean Task. Essentially, we will only want to have a dropdown of waypoints that are relevant to the selected task. Currently, the information is available as s building.yaml, but not populated the rostopic; /map. One way is to populate the GraphNode param with the relevant information about the waypoint.

I think it should work for a more permanent solution, in the meantime, I don't think it's worth it to implement the build time configuration in the old dashboard. You can just hard code the values in the client for almost the same effect.

**Comment by Yadunund** [comment]
@koonpeng @ChawinTan 
Could we also address this issue https://github.com/open-rmf/rmf-web/issues/366

Right now the Phase information dominates the task itself. It would be nicer if the phase information can be indented to represent that its belongs to the task above. Smaller fonts and perhaps no blue infill?

**Comment by koonpeng** [comment]
> Add a "Description" column to the tasks in the Tasks tab.

The task table doesn't have space for a description field, the task detailed info contains the description but due to a bug in rmf, tasks are wrongly published as "station" tasks so the fields are not shown.

**Comment by Yadunund** [comment]
@koonpeng you're right about both points. The Description is populated correctly when we use `throwaway/demo` of `rmf_ros2`. Setting the correct `RMF_SERVER_USE_SIM_TIME` value correctly updates the state of the task.

![image](https://user-images.githubusercontent.com/13482049/120308609-df639e80-c306-11eb-987b-c0d17f7b8c7c.png)

I'll check those off the list!

**Comment by Yadunund** [comment]
I guess the only pending request here is to update the visuals of the phase information 👍🏼

**Comment by Yadunund** [comment]
Closing this ticket as all the features have been added to `throwaway/demo`. Thanks everyone 🎉
