### ISSUE TITLE
Should the deploy script include the npm run setup before building the docker

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#388]
> I believe the example deployment git clones the rmf sources as part of the instructions, so you can point to script to the rmf directories via relative paths.

You mean by using the js "ament"? 

> In that case, I don't think you should be using the example scripts, you can run the setup from the dashboard before building it as part of your deployment script.

Yeah, sounds good. So there is no need for the get-icons-locally script then. So the deploy script should show the resources prompt then? 

I'll create a new issue with this and let's merge just the icon fix then

_Originally posted by @matiasbavera in https://github.com/open-rmf/rmf-web/issues/383#issuecomment-854197752_

@koonpeng  @cnboonhan

**Comment by koonpeng** [comment]
> Yeah, sounds good. So there is no need for the get-icons-locally script then. So the deploy script should show the resources prompt then?

The deploy script should not require user input, to import the resources, we can run the setup script in the dashboard dockerfile. But the problem of how/where to get the resources would be different for each deployment, for the example deployment, since we are using rmf_demos we can find the resources using ament or simply via relative path because we know where the repos are checked out. For an actual deployment, that is unlikely to be the case so the steps would be different, and that would mean different dockerfiles.

**Comment by cnboonhan** [comment]
How might a "non-example" deployment be scripted? Does `npm run setup` support some sort of preloaded yaml?

**Comment by koonpeng** [comment]
Should be addressed by #466, it shows an example of different deployment configuration with the use of kustomize.
