### ISSUE TITLE
Design: New building map panel is not well adapted to large maps

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#491]
## Feature request

As an example, this is how it looks in the clinic world

![image](https://user-images.githubusercontent.com/45189696/132184849-534eb97e-147c-43f9-8419-196e085efbd6.png)

There are lots of doors and the doors panels just ends up creating a very long scrollable list such that you cannot see the other items (lifts, dispensers, ingestors) without lots of scrolling.

The new design also loses some highly desired features like being able to locate entities by searching or clicking on the map.

**Comment by vallq** [comment]
Is this ticket available to be picked up? It's not blocked by anything else at the moment, right? Or does this need to be iterated with figma first...?

What I can think of is to have the panels (Doors, Workcells) have a fixed height (50% max height since there are 2 panels?), with vertical scrolling when needed, and to make each component box (the blue boxes) smaller when there are > x number of components, so each row can accommodate maybe 4 or 5 boxes instead.

**Comment by aaronchongth** [comment]
I think this is not blocked and can be picked up.

> What I can think of is to have the panels (Doors, Workcells) have a fixed height (50% max height since there are 2 panels?), with vertical scrolling when needed, and to make each component box (the blue boxes) smaller when there are > x number of components, so each row can accommodate maybe 4 or 5 boxes instead.

That's a good idea! This will certainly increase general quality of life when using it, I can't really imagine 4 or 5 in a row, perhaps it should be prototyped on Figma first?
