### ISSUE TITLE
[Galactic: trajectory-socket-manager.ts] Question about the existence of trajectory-socket manager 

### ISSUE THREAD

**Issue by dlfksj** [open-rmf/rmf-web#665]
Hello, thanks for sharing this repository. 
I'm trying to understand this repository, but I have a question about the existence of the trajectory socket manager.

I think the trajectory socket manager is different from the other data (fleet_state_update and task_state_update) that are sent through the rest api.

Thank you :)

**Comment by aaronchongth** [comment]
Hello! Yes it goes through a separate route. May I know what your question is?

**Comment by dlfksj** [comment]
I want to know why trajectory socket manager is located on the dashboard not on the api-server.

**Comment by aaronchongth** [comment]
That is because trajectories are handled in the RMF scheduler, which we already have a server for, https://github.com/open-rmf/rmf_visualization#websocket-server-for-custom-uis. You can find more information about the trajectory server here.

It could certainly be sent through the api-server as you surmised, but it is not information that we are interested in logging into the database for later queries. If you would like to handle trajectories in the api-server, and have a compelling reason to do so, feel free to implement it and open a PR for this new feature and we can discuss further in that ticket.

Just a note, as this is neither an issue or a bug report, please use the discussion board for questions like this in the future, https://github.com/open-rmf/rmf/discussions

**Comment by dlfksj** [comment]
Thank you for your fast reply.
I'll use the discussion board next time. Thanks!
