### ISSUE TITLE
The waypoints of the multi-floor world displays the dislocation on the map

### ISSUE THREAD

**Issue by liugehaizaixue** [open-rmf/rmf-web#679]
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  - From source
- ROS distribution and version:
  - galactic

### Description of the bug
In the web page, the waypoints of the multi-floor world displays the dislocation on the map.
I created a multi-floor world. However, after I correctly drew the path in 'traffic editor', I opened 'rmf-web' and made the following error: Except for the first floor, the point positions of other floors are misplaced. As shown in the figure below.

### Expected behavior
Waypoints should be in the correct position

### Actual behavior
Except for the first floor, the location of waypoints is chaotic

### Screenshots
![image](https://user-images.githubusercontent.com/103879998/220276681-5ca56706-53c0-42ae-84e4-3a68966ae9db.png)
![image](https://user-images.githubusercontent.com/103879998/220276754-fc8d570f-fd20-4ea7-aabc-eeb0f60786bf.png)

**Comment by aaronchongth** [comment]
Hello! This is due to the limitations of using `react-leaflet`, we are in the midst of migrating away from it. However it is not our current priority.

As a workaround, you can modify the map floor plans to have the exact same number of pixels, with the correct components layered on top of each other, example
* roscon workshop L1, https://github.com/open-rmf/roscon_workshop/blob/main/roscon_maps/maps/workshop/conference_room_b1.png
* roscon workshop L2, https://github.com/open-rmf/roscon_workshop/blob/main/roscon_maps/maps/workshop/conference_room_b1_balcony.png

Note that the floor plans are layered directly over each other, lifts are in the same pixel locations as well.

**Comment by aaronchongth** [comment]
This isfixed with the current map implementation
